name: my_app
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ Required for Firebase
  firebase_core: ^3.0.0

  # ✅ Add Firebase products you want
  firebase_auth: ^5.0.0         # Authentication
  cloud_firestore: ^5.0.0       # Firestore database
  firebase_analytics: ^11.0.0   # Analytics

  # ✅ Already in your project
  geolocator: ^10.0.0
  image_picker: ^1.0.0
  shared_preferences: ^2.0.0
  permission_handler: ^11.0.0
  google_sign_in: ^6.1.5
  supabase_flutter: ^2.9.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  # # Add Inter font
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

  # # Add assets directory for images
  # assets:
  #   # - assets/images/