// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCnHwlLzdk6Pfkj6Lm4avlqnQgsqz4xkQ',
    appId: '1:1035330986637:web:6b08d6506890d438cff8c4',
    messagingSenderId: '1035330986637',
    projectId: 'technova-app-ea5bd',
    authDomain: 'technova-app-ea5bd.firebaseapp.com',
    storageBucket: 'technova-app-ea5bd.firebasestorage.app',
    measurementId: 'G-Y4GH5B9HN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGSdnr2kB4iv4W6iRt9PzEiiG85wHq37k',
    appId: '1:1035330986637:android:508bfc088163b1b1cff8c4',
    messagingSenderId: '1035330986637',
    projectId: 'technova-app-ea5bd',
    storageBucket: 'technova-app-ea5bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN3xkVW615Bp8mFNbr7EmTB_M0VXeXr24',
    appId: '1:1035330986637:ios:9539396498099e86cff8c4',
    messagingSenderId: '1035330986637',
    projectId: 'technova-app-ea5bd',
    storageBucket: 'technova-app-ea5bd.firebasestorage.app',
    iosClientId: '1035330986637-2nqjml29eoi4fs5a7jvrerg0fkkrs9er.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN3xkVW615Bp8mFNbr7EmTB_M0VXeXr24',
    appId: '1:1035330986637:ios:9539396498099e86cff8c4',
    messagingSenderId: '1035330986637',
    projectId: 'technova-app-ea5bd',
    storageBucket: 'technova-app-ea5bd.firebasestorage.app',
    iosClientId: '1035330986637-2nqjml29eoi4fs5a7jvrerg0fkkrs9er.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCnHwlLzdk6Pfkj6Lm4avlqnQgsqz4xkQ',
    appId: '1:1035330986637:web:60b598a81280b547cff8c4',
    messagingSenderId: '1035330986637',
    projectId: 'technova-app-ea5bd',
    authDomain: 'technova-app-ea5bd.firebaseapp.com',
    storageBucket: 'technova-app-ea5bd.firebasestorage.app',
    measurementId: 'G-771PGF25PL',
  );
}
